Stop unnecessary lint/type checking for test runs
ts-jest is doing everything necessary to perform type checking and more.

```sh
15:33 $ yarn test
yarn run v1.13.0
$ jest
 PASS  src/converters.test.ts
 PASS  src/invocationValidator.test.ts
 FAIL  src/executionHandler.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/initializeContext.ts:2:3 - error TS6133: 'CreateEntityOperation' is declared but its value is never read.

    2   CreateEntityOperation,
        ~~~~~~~~~~~~~~~~~~~~~
```